name: Multi-Service Checks and dice service deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - campaign
          - character
          - chat
          - dice
          - export
          - handbook
          - setting
          - user

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry (disable venv creation)
        run: poetry config virtualenvs.create false

      - name: Install dependencies for ${{ matrix.service }}_service
        working-directory: ./${{ matrix.service }}_service
        run: poetry install --no-interaction --no-root

      - name: Run make ${{ matrix.service }}-check
        run: make ${{ matrix.service }}-check

  push-to-yandexcloud:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build docker image
        working-directory: dice_service
        run: |
          docker build . --file Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/delivery-service:latest
          
      - name: Log in YandexCloud
        uses: docker/login-action@v3
        with: 
          registry: cr.yandex 
          username: json_key 
          password: ${{ secrets.YC_KEYS }} 

      - name: Push tag to YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [push-to-yandexcloud]
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
