name: Multi-Service Checks and dice service deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - campaign
          - character
          - chat
          - dice
          - export
          - handbook
          - setting
          - user

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry (disable venv creation)
        run: poetry config virtualenvs.create false

      - name: Install dependencies for ${{ matrix.service }}_service
        working-directory: ./${{ matrix.service }}_service
        run: poetry install --no-interaction --no-root

      - name: Run make ${{ matrix.service }}-check
        run: make ${{ matrix.service }}-check

  push-to-yandexcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        working-directory: ./dice_service
        run: |
          docker build . --file Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/delivery-service:latest
          
      - name: Log in YandexCloud
        uses: docker/login-action@v3
        with: 
          registry: cr.yandex 
          username: json_key 
          password: ${{ secrets.YC_KEYS }} 

      - name: Push container to YandexCloud
        working-directory: pingService
        run: | 
          docker load --input ping-service.tar
          docker tag ping-service:latest cr.yandex/${{ secrets.YC_REGISTRY_ID }}/ping-service:latest
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/ping-service:latest

