name: Multi-Service Checks and dice service deployment

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - campaign
          - character
          - chat
          - dice
          - export
          - handbook
          - setting
          - user

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry (disable venv creation)
        run: poetry config virtualenvs.create false

      - name: Install dependencies for ${{ matrix.service }}_service
        working-directory: ./${{ matrix.service }}_service
        run: poetry install --no-interaction --no-root

      - name: Run make ${{ matrix.service }}-check
        run: make ${{ matrix.service }}-check

  dice-deploy:
    - name: Build docker image
      run: |
        docker build ./dice_service --file Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/delivery-service:latest

    - name: Login to YC Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_KEYS }}

    - name: Push tag to YC Registry
      run: |
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/delivery-service:latest

